/**
 * Email Templates Module — Versioned & HTML Escaped
 */

export interface PaymentReceiptTemplateData {
  paymentId: string;
  txHash: string;
  amount: string;
  asset: string;
  assetIssuer?: string | null;
  fromAddress: string;
  receivedAt: string;
  recipientEmail?: string;
  unsubscribeUrl?: string;
}

export interface PaymentFailureTemplateData {
  alertId: string;
  txHash?: string;
  errorReason: string;
  timestamp: string;
  recipientEmail?: string;
  unsubscribeUrl?: string;
}

/**
 * Utility for safe HTML escaping to prevent XSS / HTML injection.
 */
export function escapeHtml(value: string | number | null | undefined): string {
  if (value === null || value === undefined) return '';
  return String(value).replace(/[&<>"']/g, (char) => {
    switch (char) {
      case '&': return '&amp;';
      case '<': return '&lt;';
      case '>': return '&gt;';
      case '"': return '&quot;';
      case "'": return '&#39;';
      default: return char;
    }
  });
}

/**
 * Render Payment Receipt HTML Template (v1)
 */
export function renderPaymentReceiptTemplate(data: PaymentReceiptTemplateData): {
  subject: string;
  html: string;
  text: string;
  version: string;
} {
  const version = 'v1';
  const escapedAmount = escapeHtml(data.amount);
  const escapedAsset = escapeHtml(data.asset);
  const escapedPaymentId = escapeHtml(data.paymentId);
  const escapedTxHash = escapeHtml(data.txHash);
  const escapedFrom = escapeHtml(data.fromAddress);
  const escapedReceivedAt = escapeHtml(data.receivedAt);
  const escapedIssuer = data.assetIssuer ? escapeHtml(data.assetIssuer) : null;
  const unsubscribeUrl = data.unsubscribeUrl
    ? escapeHtml(data.unsubscribeUrl)
    : 'https://stellar-alerts.org/settings/notifications';

  const subject = `[Stellar Alerts] Payment Received: ${escapedAmount} ${escapedAsset}`;

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="x-template-version" content="${version}">
  <title>${subject}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background-color: #0f172a; color: #f8fafc; margin: 0; padding: 24px; }
    .card { max-width: 600px; margin: 0 auto; background: #1e293b; border-radius: 12px; padding: 32px; border: 1px solid #334155; }
    .header { border-bottom: 1px solid #334155; padding-bottom: 16px; margin-bottom: 24px; }
    .title { color: #38bdf8; font-size: 20px; font-weight: bold; margin: 0; }
    .row { display: flex; justify-content: space-between; margin-bottom: 12px; font-size: 14px; }
    .label { color: #94a3b8; font-weight: 500; }
    .value { color: #f1f5f9; font-family: monospace; word-break: break-all; }
    .footer { margin-top: 32px; border-top: 1px solid #334155; padding-top: 16px; font-size: 12px; color: #64748b; text-align: center; }
    .footer a { color: #38bdf8; text-decoration: none; }
  </style>
</head>
<body>
  <div class="card">
    <div class="header">
      <h1 class="title">⚡ Stellar Payment Notification</h1>
    </div>
    <div class="row">
      <span class="label">Amount:</span>
      <span class="value" style="color: #4ade80; font-weight: bold;">${escapedAmount} ${escapedAsset}</span>
    </div>
    <div class="row">
      <span class="label">Payment ID:</span>
      <span class="value">${escapedPaymentId}</span>
    </div>
    <div class="row">
      <span class="label">Transaction Hash:</span>
      <span class="value">${escapedTxHash}</span>
    </div>
    <div class="row">
      <span class="label">From Address:</span>
      <span class="value">${escapedFrom}</span>
    </div>
    ${
      escapedIssuer
        ? `<div class="row"><span class="label">Asset Issuer:</span><span class="value">${escapedIssuer}</span></div>`
        : ''
    }
    <div class="row">
      <span class="label">Received At:</span>
      <span class="value">${escapedReceivedAt}</span>
    </div>
    <div class="footer">
      <p>Template Version: ${version} | Generated by Stellar Alerts</p>
      <p>To manage email alerts or unsubscribe, visit your <a href="${unsubscribeUrl}">Notification Preferences</a>.</p>
    </div>
  </div>
</body>
</html>`;

  const text = `Stellar Payment Received: ${data.amount} ${data.asset}\nPayment ID: ${data.paymentId}\nTx Hash: ${data.txHash}\nFrom: ${data.fromAddress}\nReceived At: ${data.receivedAt}`;

  return { subject, html, text, version };
}

/**
 * Render Payment/Alert Failure HTML Template (v1)
 */
export function renderPaymentFailureTemplate(data: PaymentFailureTemplateData): {
  subject: string;
  html: string;
  text: string;
  version: string;
} {
  const version = 'v1';
  const escapedAlertId = escapeHtml(data.alertId);
  const escapedTxHash = data.txHash ? escapeHtml(data.txHash) : 'N/A';
  const escapedReason = escapeHtml(data.errorReason);
  const escapedTimestamp = escapeHtml(data.timestamp);
  const unsubscribeUrl = data.unsubscribeUrl
    ? escapeHtml(data.unsubscribeUrl)
    : 'https://stellar-alerts.org/settings/notifications';

  const subject = `[Stellar Alerts] Alert Delivery Failure Notice`;

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="x-template-version" content="${version}">
  <title>${subject}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background-color: #0f172a; color: #f8fafc; margin: 0; padding: 24px; }
    .card { max-width: 600px; margin: 0 auto; background: #1e293b; border-radius: 12px; padding: 32px; border: 1px solid #ef4444; }
    .header { border-bottom: 1px solid #334155; padding-bottom: 16px; margin-bottom: 24px; }
    .title { color: #f87171; font-size: 20px; font-weight: bold; margin: 0; }
    .row { display: flex; justify-content: space-between; margin-bottom: 12px; font-size: 14px; }
    .label { color: #94a3b8; font-weight: 500; }
    .value { color: #f1f5f9; font-family: monospace; word-break: break-all; }
    .reason { background: #450a0a; border: 1px solid #991b1b; padding: 12px; border-radius: 6px; color: #fca5a5; font-family: monospace; font-size: 13px; margin: 16px 0; }
    .footer { margin-top: 32px; border-top: 1px solid #334155; padding-top: 16px; font-size: 12px; color: #64748b; text-align: center; }
    .footer a { color: #38bdf8; text-decoration: none; }
  </style>
</head>
<body>
  <div class="card">
    <div class="header">
      <h1 class="title">⚠️ Alert Delivery Failure</h1>
    </div>
    <div class="row">
      <span class="label">Alert Job ID:</span>
      <span class="value">${escapedAlertId}</span>
    </div>
    <div class="row">
      <span class="label">Transaction Hash:</span>
      <span class="value">${escapedTxHash}</span>
    </div>
    <div class="row">
      <span class="label">Failure Timestamp:</span>
      <span class="value">${escapedTimestamp}</span>
    </div>
    <div class="reason">
      <strong>Failure Detail:</strong><br>${escapedReason}
    </div>
    <div class="footer">
      <p>Template Version: ${version} | Generated by Stellar Alerts System</p>
      <p>To manage email alerts or unsubscribe, visit your <a href="${unsubscribeUrl}">Notification Preferences</a>.</p>
    </div>
  </div>
</body>
</html>`;

  const text = `Alert Delivery Failure Notice\nAlert ID: ${data.alertId}\nTx Hash: ${data.txHash ?? 'N/A'}\nReason: ${data.errorReason}\nTimestamp: ${data.timestamp}`;

  return { subject, html, text, version };
}
